#!/usr/bin/env perl
use strict;
use warnings;

use above "Genome";
use Test::More;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

use_ok('Genome::Taxon');

my $id = -54321;
my $taxon = Genome::Taxon->get($id);
ok(!$taxon, 'taxon does not exist');

$taxon = Genome::Taxon->create(
    id => $id,
    name => 'Wookiee',
    domain => 'Unknown',
    strain_name => 'Short Hair',
    species_latin_name => 'Kashyyyk Wookiee',
    #ncbi_taxon_id => 
    #ncbi_taxon_species_name => 
    #locus_tag => 
    gram_stain_category => 'NA',
    estimated_genome_size => 7000000000,
    #current_default_org_prefix => 
    #current_genome_refseq_id => 
    #model_member_id => 
    #_legacy_org_id => set in create
    #_next_amplicon_iteration => set in create
);
ok($taxon, "created a new genome taxon");
isa_ok($taxon, 'Genome::Taxon');
is($taxon->id, $id, "id is set");
is($taxon->subject_type, 'organism taxon', 'subject type is organism taxon');
print Data::Dumper::Dumper($taxon);

my $commit = eval{ UR::Context->commit; };
ok($commit, 'commit');

$taxon = Genome::Taxon->get($id);
ok($taxon, 'got new taxon');

done_testing();
exit();

