#!/usr/bin/env perl

use strict;
use warnings;

use above "Genome";

use Test::More;

$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
$ENV{UR_DBI_NO_COMMIT} = 1;

class Urt::Item {
    has => [ name => { is => 'Text', }, ],
};
sub Urt::Item::__display_name__ { return $_[0]->name; };

my @items;
for my $i (1..2) {
    unshift @items, Urt::Item->create(name => 'number '.$i);
}
is(@items, 2, 'create items');

my $remove_command = Genome::Command::Remove->create(items => \@items);
ok($remove_command, 'create remove command');
$remove_command->dump_status_messages(1);
ok($remove_command->execute(), "command succeeded");
is_deeply([ Urt::Item->get() ], [], 'removed items');

done_testing();
exit;

