#!/gsc/bin/perl

use strict;
use warnings;

use above "Genome";
use File::Temp;
use Test::More tests => 7;
use Data::Dumper;
use File::Compare;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

BEGIN {
    use_ok( 'Genome::Model::Tools::DetectVariants2::Filter::LibrarySupport');
};

my $test_input_dir  = '/gsc/var/cache/testsuite/data/Genome-Model-Tools-DetectVariants2-Filter-SomaticScoreMappingQuality/';
my $refseq = Genome::Config::reference_sequence_directory() . '/NCBI-human-build36/all_sequences.fa';
my $tumor_bam_file  = $test_input_dir . 'tumor.tiny.bam';

my $input_directory = "/gsc/var/cache/testsuite/data/Genome-Model-Tools-DetectVariants2-Filter-LibrarySupport/";
my $test_output_dir = File::Temp::tempdir('Genome-Model-Tools-DetectVariants2-Filter-LibrarySupport-XXXXX', DIR => '/gsc/var/cache/testsuite/running_testsuites', CLEANUP => 1);
my $hq_output = "$test_output_dir/indels.hq";
my $lq_output = "$test_output_dir/indels.lq";
my $expected_hq_output = "$input_directory/indels.hq.expected";
my $expected_lq_output = "$input_directory/indels.lq.expected";

my $library_support_filter = Genome::Model::Tools::DetectVariants2::Filter::LibrarySupport->create(
    input_directory => $input_directory,
    output_directory => $test_output_dir,
    aligned_reads_input => $tumor_bam_file,
    reference_sequence_input => $refseq,
);

ok($library_support_filter, "created LibrarySupportFilter object");
ok($library_support_filter->execute(), "executed LibrarySupportFilter");

ok(-s $hq_output ,'HQ output exists and has size');
ok(-s $lq_output,'LQ output exists and has size'); 

is(compare($hq_output, $expected_hq_output), 0, 'hq output matched expected output');
is(compare($lq_output, $expected_lq_output), 0, 'lq output matched expected output');
