#!/gsc/bin/perl

use strict;
use warnings;

use above "Genome";
use File::Temp;
use Test::More tests => 9;
use Data::Dumper;
use File::Compare;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

BEGIN {
    use_ok( 'Genome::Model::Tools::DetectVariants2::Filter::PindelReadSupport')
};

my $refbuild_id = 101947881;
my $input_directory = "/gsc/var/cache/testsuite/data/Genome-Model-Tools-DetectVariants2-Filter-PindelReadSupport";

# Updated to v2 to allow for new columns 
my $expected_dir = $input_directory . "/expected_v2/mod/";
my $tumor_bam_file  = $input_directory. '/flank_tumor_sorted.bam';
my $normal_bam_file  = $input_directory. '/flank_normal_sorted.bam';
my $test_output_dir = File::Temp::tempdir('Genome-Model-Tools-DetectVariants2-Filter-PindelReadSupport-XXXXX', DIR => '/gsc/var/cache/testsuite/running_testsuites', CLEANUP => 1);

my $hq_output_bed = "$test_output_dir/indels.hq.bed";
my $read_support_output_bed = "$test_output_dir/indels.hq.read_support.bed";
my $lq_output_bed = "$test_output_dir/indels.lq.bed";

my $expected_hq_bed_output = "$expected_dir/indels.hq.bed";
my $expected_lq_bed_output = "$expected_dir/indels.lq.bed";
my $expected_read_support_output = "$expected_dir/indels.hq.read_support.bed";

my $pindel_read_support = Genome::Model::Tools::DetectVariants2::Filter::PindelReadSupport->create(
    input_directory => $input_directory."/old_input",#"/pindel-somatic-calls-v1-",
    detector_directory => $input_directory,
    output_directory => $test_output_dir,
    aligned_reads_input => $tumor_bam_file,
    control_aligned_reads_input => $normal_bam_file,
    reference_build_id => $refbuild_id,
);

ok($pindel_read_support, "created PindelReadSupport object");
ok($pindel_read_support->execute(), "executed PindelReadSupport");

ok(-s $hq_output_bed ,'HQ bed output exists and has size');
ok(-e $lq_output_bed,'LQ bed output exists'); 
ok(-s $read_support_output_bed,'Read Support bed output exists and has size'); 

is(compare($hq_output_bed, $expected_hq_bed_output), 0, 'hq bed output matched expected output');
is(compare($read_support_output_bed, $expected_read_support_output), 0, 'Read Support bed output matched expected output');
is(compare($lq_output_bed, $expected_lq_bed_output), 0, 'lq bed output matched expected output');
