#!/gsc/bin/perl

use strict;
use warnings;

use above "Genome";
use Test::More tests => 9;
use Genome::Utility::MetagenomicClassifier::ChimeraClassifier;

my $cc_broad = Genome::Utility::MetagenomicClassifier::ChimeraClassifier->create(
        training_set => 'broad',
    );
    ok($cc_broad, 'Created chimera classifier');

    my $seq = Bio::Seq->new( 
        -display_id => 'S000002017 Pirellula staleyi', 
        -seq => 'AATGAACGTTGGCGGCATGGATTAGGCATGCAAGTCGTGCGCGATATGTAGCAATACATGGAGAGCGGCGAAAGGGAGAGTAATACGTAGGAACCTACCTTCGGGTCTGGGATAGCGGCGGGAAACTGCCGGTAATACCAGATGATGTTTCCGAACCAAAGGTGTGATTCCGCCTGAAGAGGGGCCTACGTCGTATTAGCTAGTTGGTAGGGTAATGGCCTACCAAGnCAAAGATGCGTATGGGGTGTGAGAGCATGCCCCCACTCACTGGGACTGAGACACTGCCCAGACACCTACGGGTGGCTGCAGTCGAGAATCTTCGGCAATGGGCGAAAGCCTGACCGAGCGATGCCGCGTGCGGGATGAAGGCCTTCGGGTTGTAAACCGCTGTCGTAGGGGATGAAGTGCTAGGGGGTTCTCCCTCTAGTTTGACTGAACCTAGGAGGAAGGnCCGnCTAATCTCGTGCCAGCAnCCGCGGTAATACGAGAGGCCCAnACGTTATTCGGATTTACTGGGCTTAAAGAGTTCGTAGGCGGTCTTGTAAGTGGGGTGTGAAATCCCTCGGCTCAACCGAGGAACTGCGCTCCAnACTACAAGACTTGAGGGGGATAGAGGTAAGCGGAACTGATGGTGGAGCGGTGAAATGCGTTGATATCATCAGGAACACCGGAGGCGAAGGCGGCTTACTGGGTCCTTTCTGACGCTGAGGAACGAAAGCTAGGGGAGCAnACGGGATTAGATACCCCGGTAGTCCTAnCCGTAAACGATGAGCACTGGACCGGAGCTCTGCACAGGGTTTCGGTCGTAGCGAAAGTGTTAAGTGCTCCGCCTGGGGAGTATGGTCGCAAGGCTGAAACTCAAAGGAATTGACGGGGGCTCACACAAGCGGTGGAGGATGTGGCTTAATTCGAGGCTACGCGAAGAACCTTATCCTAGTCTTGACATGCTTAGGAATCTTCCTGAAAGGGAGGAGTGCTCGCAAGAGAGCCTnTGCACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTCGTGAGATGTCGGGTTAAGTCCCTTAACGAGCGAAACCCTnGTCCTTAGTTACCAGCGCGTCATGGCGGGGACTCTAAGGAGACTGCCGGTGTTAAACCGGAGGAAGGTGGGGATGACGTCAAGTCCTCATGGCCTTTATGATTAGGGCTGCACACGTCCTACAATnGTGCACACAAAGCGACGCAAnCTCGTGAGAGCCAGCTAAGTTCGGATTGCAGGCTGCAACTCGCCTGCATGAAGCTGGAATCGCTAGTAATCGCGGGTCAGCATACCGCGGTGAATGTGTTCCTGAGCCTTGTACACACCGCCCGTCAAGCCACGAAAGTGGGGGGGACCCAACAGCGCTGCCGTAACCGCAAGGAACAAGGCGCCTAAGGTCAACTCCGTGATTGGGACTAAGTCGTAACAAGGTAGCCGTAGGGGAACCTGCGGCTGGATCACCTCCTT',
    );
    my $classification = $cc_broad->classify($seq);
    ok($classification, 'got classification from classifier ' . $classification);
    isa_ok($classification, 'Genome::Utility::MetagenomicClassifier::ChimeraClassification');

    ok ($classification->divergent_genera_count == 0, "no divergent genera");
    ok( $classification->maximum_common_depth == 6, "correct lca");

    my $chimeric_seq = Bio::Seq->new( 
        -display_id => 'chimera', 
        -seq => 'GAGTTTGATTCTGGCTCAGGATGAACGCTAGCTACAGGCTTAACACATGCAAGTCGAGGGGCAGCATGGTCTTAGCTTGCTAAGGCCGATGGCGACCGGCGCACGGGTGAGTAACACGTATCCAACCTGCCGTCTACTCTTGGACAGCCTTCTGAAAGGAAGATTAATACAAGATGGCATCATGAGTCCGCATGTTCACATGATTAAAGGTATTCCGGTAGACGATGGGGATGCGTTCCATTAGATAGTAGGCGGGGTAACGGCCCACCTAGTCTTCGATGGATAGGGGTTCTGAGAGGAAGGTCCCCCACATTGGAACTGAGACACGGTCCAAACTCCTACGGGAGGCAGCAGTGAGGAATATTGGTCAATGGGCGAGAGCCTGAACCAGCCAAGTAGCGTGAAGGATGACTGCCCTATGGGTTGTAAACTTCTTTTATAAAGGAATAAAGTCGGGTATGCATACCCGTTTGCATGTACTTTATGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGATGGATGTTTAAGTCAGTTGTGAACCGGCGTACTCCCCAGGTGGGATGCTTAACGCTTTCGCTTGGTCACTGACCATAAGGGCCAACAACGAGCATCCATCGTTTACCGCGTGGACTACCAGGGTATCTAATCCTGTTCGATACCCACGCTTTCGAGCATCAGCGTCAGTTGCGCTACAGTAAGCTGCCTTCGCAATCGGAGTTCTTCGTGATATCTAAGCATTTCACCGCTACACCACGAATTCCGCCTACTTTCGGCGCACTCAAGCCCCCCAGTTCGCGCTGCAAGTCGGACGTTGAGCACCCGCATTTCACAACACGCTTAAGAGGCGGCCTACGCTCCCTTTAAACCCAATAAATCCGGATAACGCCTGGACCTTCCGTATTACCGCGGCTGCTGGCACGGAATTAGCCGGTCCTTATTCATGCGGTACCTGCAAAAACCCACACGTGGGCTCTTTTATCCCCGCATAAAAGCAGTTTACAACCCATAGGGCCGTCATCCTGCACGCTACTTGGCTGGTTCAGGCTTACGCCCATTGACCAATATTCCTCACTGCTGCCTCCCGTAGGAGTCTGGACCGTGTCTCAGTTCCAGTGTGGGGGACCTTCCTCTCAGAACCCCTACCGATCGTGGCCACGGTGGGCCGTTACCCCGCCGTCAAGCTAATCGGACGCATCCCCATCCTTTACCGCTAAGCCTTTGGTCCAAATCGGATGCCGTCAATGGACTACATACGGTATTAGTCCGACTTTCGCCGGGTTATCCCGTAGTAAAGGGTAGGTTGGATACGCGTTACTCACCCGTGCGCCGGTCGCCATCAGTAATTGCAAGCAATCActAtGCTGCCCCGCGACTTGCATGTGTTAAGCCTGTAGCtagcgttcatcctgagccagaatcaaactc',
    );

    $classification = $cc_broad->classify($chimeric_seq);
    ok($classification, 'got classification from classifier');
    isa_ok($classification, 'Genome::Utility::MetagenomicClassifier::ChimeraClassification');

    my $divergent_count = $classification->divergent_genera_count;
    ok ($divergent_count > 0, "$divergent_count divergent genera");
    ok( $classification->maximum_common_depth < 6, "correct lca");

    done_testing();
    exit;

