#!/gsc/bin/perl

BEGIN { 
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use strict;
use warnings;

use above "Genome";
use Test::More;

use_ok('Genome::Data::Comparer') or die;

my $data_dir = "/tmp/testComparer/";
my $comparer = Genome::Data::Comparer->create(to_file => $data_dir."same",
                                              to_file_different_1 => $data_dir."different_1",
                                              to_file_different_2 => $data_dir."different_2",
                                              from_file => "/gscuser/aregier/test/annotate/dbSnpOut.ours.ensemblOnly.noHeader",
                                              from_file2 => "/tmp/dbSnpTopEffects.vcf.tgi.noSKIP.sorted",
                                              to_format => "tgi",
                                              from_format => "tgi",
                                          );
ok($comparer, 'successfully made comparer object');

$comparer->convert_all();

done_testing();
