#!/usr/bin/env perl
use strict;
use warnings;
unless (@ARGV) {
    die "Usage: add-pkg DEBNAME DEBNAME...\n";
}

for my $deb (@ARGV) {
    my $version = `dpkg -l $deb | tail -n 1 | awk '{ print \$3 }'`;
    unless ($version) {
        die "failed to find debian package $deb\n";
    }
    chomp $version;
    print "version $version\n";

    my $rname = `dpkg -L $deb | grep NAMESPACE`;
    unless ($rname) {
        die "failed to find an R package name in the dpkg -L output for $deb\n";
    }
    chomp $rname;
    $rname =~ s/.NAMESPACE//;
    $rname =~ s/^.*\///;
    print "rname: $rname\n";

    sub run {
        my $cmd = shift;
        print "RUN: $cmd\n";
        my $rv = system $cmd;
        $rv /= 256;
        if ($rv) {
            die "ERROR: $!\n";
        }
    }

    run "echo '$rname' >> base-list";
    run "echo 'library($rname)' >> test.R";
    run "echo '$deb (>= $version)' >> ubuntu-lucid-list";
    run "tail base-list test.R ubuntu-lucid-list";
}

