#!/usr/bin/env perl
use strict;
use warnings;
unless (@ARGV) {
    die "Usage: add-pkg DEBNAME ...\n";
}

for my $deb (@ARGV) {
    my $version = `dpkg -l $deb | tail -n 1 | awk '{ print $3 }'`;
    unless ($version) {
        die "failed to find debian package $deb\n";
    }

    my $rname = `dpkg -L r-cran-pbh5 | grep NAMESPACE | sed s/.NAMESPACE// | sed s/^.*\\///`;
    unless ($rname) {
        die "failed to find an R package name in the dpkg -L output\n";
    }
    
    sub run {
        my $cmd = shift;
        print "RUN: $cmd\n";
        my $rv = system $cmd;
        $rv /= 256;
        if ($rv) {
            die "ERROR: $!\n";
        }
    }

    run "echo '$rname' >> base-list";
    run "echo 'library($rname)' >> test.R";
    run "echo '$deb (>= $version)' >> ubuntu-lucid-list";
}

