package Genome::Model::Command::Define;

use strict;
use warnings;

use Genome;
use Genome::Model::Command::Define::Helper;

class Genome::Model::Command::Define {
    is => 'Command::SubCommandFactory', 
    is_abstract => 1,
};

# Compiling this class autogenerates one sub-command per processing profile.
# These are the commands which actually execute, and either inherit from this
# class or from those returned by _sub_commands_inherit_from.
sub _sub_commands_from { 'Genome::ProcessingProfile' }

# Sub commands generated by this class will inherit from the class(es) specified here.
sub _sub_commands_inherit_from {'Genome::Model::Command::Define::Helper'}

1;

