#!/usr/bin/env perl

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
};

use strict;
use warnings;

use above 'Genome';

use Test::More;

use_ok('Genome::Model::Command::Input::Update') or die;

class Shape { is => 'UR::Object', id_by => 'name', has => [ name =>  { is => 'Text', }, ], };
sub Shape::__display_name__ { return $_[0]->name.' ('.$_[0]->id.')'; };
my $square = Shape->create(name => 'square');
ok($square, 'create a square');
my $circle = Shape->create(name => 'circle');
ok($circle, 'create a circle');
class Genome::ProcessingProfile::Tester {
    is => 'Genome::ProcessingProfile',
};
my $sample = Genome::Sample->create(name => '__SAMPLE__');
ok($sample, 'create sample');
my $pp = Genome::ProcessingProfile::Tester->create(name => '__PP__');
ok($pp, 'create pp');
class Genome::Model::Tester {
    is => 'Genome::Model',
    has => [
        color => {
            is => 'Text',
            via => 'inputs',
            to => 'value_id',
            where => [ name => 'color', value_class_name => 'UR::Value', ],
            is_many => 0,
            is_mutable => 1,
        },
        purpose => {
            is => 'Text',
            via => 'inputs',
            to => 'value_id',
            where => [ name => 'purpose', value_class_name => 'UR::Value', ],
            is_many => 0,
            is_mutable => 1,
            is_optional => 1,
        },
        shape => {
            is => 'Shape',
            via => 'inputs',
            to => 'value',
            where => [ name => 'shape', value_class_name => 'Shape', ],
            is_many => 0,
            is_mutable => 1,
            is_optional => 1,
        },
        lots => {
            is => 'UR::Value',
            via => 'inputs',
            to => 'value',
            where => [ name => 'lots', value_class_name => 'UR::Value', ],
            is_mutable => 1,
            is_optional => 1,
            is_many => 1,
        },
    ],
};
my $model = Genome::Model::Tester->create(
    name => '__MODEL__',
    subject => $sample,
    processing_profile => $pp,
    color => 'red',
    purpose => 'fun',
    shape => $square,
);
ok($model, 'create model') or die;
is($model->color, 'red', 'set color on create');
is($model->purpose, 'fun', 'set purpose on create');
is_deeply($model->shape, $square, 'set shape on create');
my @input_value_ids = sort map { $_->value_id } $model->inputs;
is_deeply(\@input_value_ids, [qw/ fun red square /], 'inputs match');
ok(!eval{ $model->shape('yellow'); }, 'failed to set shape to a string');

my $update = Genome::Model::Command::Input::Update->create(
    model => $model,
    name => 'color',
    value => 'blue',
);
ok($update, 'create');
$update->dump_status_messages(1);
ok($update->execute, 'execute - update property');
is($model->color, 'blue', 'color is now blue');

$update = Genome::Model::Command::Input::Update->create(
    model => $model,
    name => 'purpose',
);
ok($update, 'create');
$update->dump_status_messages(1);
ok($update->execute, 'execute - update optional property to NULL');

$update = Genome::Model::Command::Input::Update->create(
    model => $model,
    name => 'shape',
    value => 'name=circle',
);
ok($update, 'create');
$update->dump_status_messages(1);
ok($update->execute, 'execute - update shape');
is_deeply([$model->shape], [$circle], 'execute - update shape to circle');

# fails
$update = Genome::Model::Command::Input::Update->create(
    model => $model,
    name => 'shape',
    value => 'name=yellow',
);
ok($update, 'create');
$update->dump_status_messages(1);
ok(!$update->execute, 'execute failed to update where the value object does not exist');

$update = Genome::Model::Command::Input::Update->create(
    model => $model,
    name => 'shape_id',
    value => 'name=circle',
);
ok($update, 'create');
$update->dump_status_messages(1);
ok(!$update->execute, 'execute failed to update non input');

$update = Genome::Model::Command::Input::Update->create(
    model => $model,
    name => 'not_a_property',
);
ok($update, 'create');
$update->dump_status_messages(1);
ok(!$update->execute, 'execute failed to update non property');

$update = Genome::Model::Command::Input::Update->create(
    model => $model,
    name => 'color',
);
ok($update, 'create');
$update->dump_status_messages(1);
ok(!$update->execute, 'execute failed to update required property to NULL');

$update = Genome::Model::Command::Input::Update->create(
    model => $model,
    name => 'lots',
    value => 'Watson',
);
ok($update, 'create');
$update->dump_status_messages(1);
ok(!$update->execute, 'execute failed to update "lots" - an "is_many" property');

done_testing();
exit;

