#!/gsc/bin/perl

use strict;
use warnings;

use File::Path;
use Test::More;

use above 'Genome';

BEGIN {
    if (`uname -a` =~ /x86_64/) {
        plan tests => 10;
    } else {
        plan skip_all => 'Must run on a 64 bit machine';
    }
    use_ok('Genome::InstrumentData::Solexa');
    use_ok('Genome::InstrumentData::Command::Align::Maq');
}

$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
$ENV{UR_DBI_NO_COMMIT} = 1;

my $gerald_directory = '/gsc/var/cache/testsuite/data/Genome-InstrumentData-Align-Maq/test_sample_name';

# Existing
my $instrument_data = Genome::InstrumentData::Solexa->create(
                                                             id => 'test_instrument_data_id',
                                                             sequencing_platform => 'solexa',
                                                             sample_name => 'test_sample_name',
                                                             run_name => 'test_run_name',
                                                             subset_name => 4,
                                                             run_type => 'Paired End Read 1',
                                                             gerald_directory => $gerald_directory,
                                                         );
isa_ok($instrument_data,'Genome::InstrumentData::Solexa');
ok($instrument_data->is_paired_end,'instrument data is paired end');

# TODO: create mock event or use some fake event for logging

# once to find old data
my $dir = $instrument_data->find_or_generate_alignments_dir(
                                                            aligner_name => 'maq',
                                                            adaptor_flag => 'dna',
                                                            version => '0.6.8', 
                                                            reference_name => 'refseq-for-test',
                                                            event_id => 95637502
                                                        );
ok($dir, "alignments found/generated");
ok(-d $dir, "result is a real directory");
my $expected_dir = Genome::Config->root_directory . '/alignment_links/maq0_6_8/refseq-for-test/test_run_name/4_'. $instrument_data->id;
is($dir,$expected_dir, 'directory is the expected value');


$instrument_data = Genome::InstrumentData::Solexa->create(
                                                          sequencing_platform => 'solexa',
                                                          sample_name => 'test_sample_name',
                                                          run_name => 'test_run_name',
                                                          subset_name => 4,
                                                          run_type => 'Paired End Read 1',
                                                          gerald_directory => '/gsc/var/cache/testsuite/data/Genome-InstrumentData-Align-Maq/test_sample_name',
                                                      );
# once to make new data
my $dir2 = $instrument_data->find_or_generate_alignments_dir(
                                                             aligner_name => 'maq',
                                                             adaptor_flag => 'dna',
                                                             version => '0.6.5',
                                                             reference_name => 'refseq-for-test',
                                                             event_id => 95637502
                                                         );
ok($dir2, "alignments found/generated");
ok(-d $dir2, "result is a real directory");
my $expected_dir2 = Genome::Config->root_directory .'/alignment_links/maq0_6_5/refseq-for-test/test_run_name/4_'. $instrument_data->id;
is($dir2,$expected_dir2, 'directory is the expected value');

rmtree $expected_dir2;

exit;
