#!/usr/bin/env perl

use strict;
use warnings;

BEGIN {
    $ENV{NO_LSF} = 1;
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
};

use above 'Genome';
use Genome::SoftwareResult;

use Test::More;
use File::Compare;

my $archos = `uname -a`;
if ($archos !~ /64/) {
    plan skip_all => "Must run from 64-bit machine";
}

use_ok('Genome::Model::Tools::DetectVariants2::Breakdancer');

my $refbuild_id = 101947881;
my $ref_seq_build = Genome::Model::Build::ImportedReferenceSequence->get($refbuild_id);
ok($ref_seq_build, 'human36 reference sequence build') or die;

no warnings;
# Override lock name because if people cancel tests locks don't get cleaned up.
*Genome::SoftwareResult::_resolve_lock_name = sub {
    return Genome::Sys->create_temp_file_path;
};
use warnings;

my $test_dir = '/gsc/var/cache/testsuite/data/Genome-Model-Tools-DetectVariants2-Breakdancer';
my $test_base_dir = File::Temp::tempdir('DetectVariants2-Breakdancer-XXXXX', DIR => '/gsc/var/cache/testsuite/running_testsuites/', CLEANUP => 1);
my $test_working_dir = "$test_base_dir/output";

my $normal_bam = $test_dir . '/normal.bam';
my $tumor_bam  = $test_dir . '/tumor.bam';
my $cfg_file   = $test_dir . '/breakdancer_config';

my $chromosome = 22;
my $expected_output = join "/", ($test_dir, "svs.hq.$chromosome".'_current');
my $test_out   = $test_working_dir . '/' . $chromosome . '/svs.hq.'.$chromosome;

my $version = '1.2';
note("use breakdancer version: $version");

my $command = Genome::Model::Tools::DetectVariants2::Breakdancer->create(
    reference_build_id => $refbuild_id,
    aligned_reads_input => $tumor_bam,
    control_aligned_reads_input => $normal_bam,
    version => $version,
    params  => '-g -h:-a -q 10 -o',  #breakdancer 1.2 and beyond need turn on "-a" flag to output lib info
    chromosome => $chromosome,
    output_directory => $test_working_dir,
    config_file => $cfg_file,
);
ok($command, 'Created `gmt detect-variants2 breakdancer` command');
$command->dump_status_messages(1);
ok($command->execute, 'Executed `gmt detect-variants2 breakdancer` command');

is(compare($expected_output, $test_out), 0, "svs.hq output as expected");

done_testing();
exit;
