#! /gsc/bin/perl

use strict;
use warnings;

use above 'Genome';

use Test::More;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
UR::DataSource->next_dummy_autogenerated_id;
do {
    $UR::DataSource::last_dummy_autogenerated_id = int($UR::DataSource::last_dummy_autogenerated_id / 10);
} until length($UR::DataSource::last_dummy_autogenerated_id) < 9;
diag('Dummy ID: '.$UR::DataSource::last_dummy_autogenerated_id);
cmp_ok(length($UR::DataSource::last_dummy_autogenerated_id), '<',  9, 'dummy id is shorter than 9 chars');

use_ok('Genome::Sample::Command::Import') or die;

# some params
#my $individual_name = 'H_KA-02-01G';
my $individual_name = 'TCGA-HUMAN-TEST';
my $sample_name = 'TCGA-HUMAN-TEST-1';

# fail - invalid taxon
my $import = Genome::Sample::Command::Import->create(
    taxon_name => 'klingon',
    individual_name => $individual_name,
    sample_name => $sample_name,
    library_type => 'extlibs',
);
$import->dump_status_messages(1);
ok($import, 'create');
ok(!$import->execute, 'exectue failed as expected w/ invalid taxon');

# sucess
$import = Genome::Sample::Command::Import->create(
    taxon_name => 'human',
    individual_name => $individual_name,
    sample_name => $sample_name,
    library_type => '-extlibs',
    sample_attrs => 'organ_name=blood,tissue_desc=G_DNA_blood' # these exist
);
$import->dump_status_messages(1);
ok($import, 'create');
ok($import->execute, 'execute');

UR::Context->commit or die;

my $indiviudal = Genome::Individual->get(name => $individual_name);
ok($indiviudal, 'created indiviudal');
my $sample = Genome::Sample->get(name => $sample_name);
ok($sample, 'created sample');
my $library = Genome::Library->get(sample_id => $sample->id);
ok($library, 'created library');

done_testing();
exit;

=pod

=head1 Tests

=head1 Disclaimer

 Copyright (C) 2010 Washington University Genome Sequencing Center

 This script is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY or the implied warranty of MERCHANTABILITY
 or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 License for more details.

=head1 Author(s)

 Eddie Belter <ebelter@watson.wustl.edu>

=cut

