DROP TABLE IF EXISTS drug_gene_interaction_attribute;
DROP TABLE IF EXISTS drug_gene_interaction;
DROP TABLE IF EXISTS gene_name_category_association;
DROP TABLE IF EXISTS gene_name_association;
DROP TABLE IF EXISTS drug_name_category_association;
DROP TABLE IF EXISTS drug_name_association;
DROP TABLE IF EXISTS drug_name;
DROP TABLE IF EXISTS gene_name;

create table drug_name (
        id varchar NOT NULL,
        name varchar NOT NULL,
        description text,
        nomenclature varchar NOT NULL,
        source_db_name varchar NOT NULL,
        source_db_version varchar NOT NULL,
        PRIMARY KEY (id)
);

create table drug_name_association (
        id varchar NOT NULL,
        drug_name_id varchar NOT NULL,
        alternate_name varchar NOT NULL,
        description text,
        nomenclature varchar NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY(drug_name_id) REFERENCES drug_name(id)
);

create table drug_name_category_association (
        id varchar NOT NULL,
        drug_name_id varchar NOT NULL,
        category_name varchar NOT NULL,
        description text,
        PRIMARY KEY (id),
        FOREIGN KEY(drug_name_id) REFERENCES drug_name(id)
);

create table gene_name (
        id varchar NOT NULL,
        name varchar NOT NULL,
        description text,
        nomenclature varchar NOT NULL,
        source_db_name varchar NOT NULL,
        source_db_version varchar NOT NULL,
        PRIMARY KEY (id)
);

create table gene_name_association (
        id varchar NOT NULL,
        gene_name_id varchar NOT NULL,
        alternate_name varchar NOT NULL,
        description text,
        nomenclature varchar NOT NULL,
        PRIMARY KEY (id),
        FOREIGN KEY(gene_name_id) REFERENCES gene_name(id)
);

create table gene_name_category_association (
        id varchar NOT NULL,
        gene_name_id varchar NOT NULL,
        category_name varchar NOT NULL,
        description text,
        PRIMARY KEY (id),
        FOREIGN KEY(gene_name_id) REFERENCES gene_name(id)
);

create table drug_gene_interaction (
        id varchar NOT NULL,
        drug_name_id varchar NOT NULL,
        gene_name_id varchar NOT NULL,
        interaction_type varchar NOT NULL,
        description text,
        PRIMARY KEY(id),
        FOREIGN KEY(drug_name_id) REFERENCES drug_name(id),
        FOREIGN KEY(gene_name_id) REFERENCES gene_name(id),
        UNIQUE (drug_name_id, gene_name_id, interaction_type)
);

create table drug_gene_interaction_attribute (
        id varchar NOT NULL,
        interaction_id varchar NOT NULL REFERENCES drug_gene_interaction(id),
        name varchar NOT NULL,
        value varchar NOT NULL,
        PRIMARY KEY (id)
);
