DROP TABLE IF EXISTS genome_task;
DROP TABLE IF EXISTS project_part;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS genome_user;
DROP TABLE IF EXISTS subject_attribute;
DROP TABLE IF EXISTS subject;
DROP TABLE IF EXISTS misc_note;

CREATE TABLE misc_note (
    editor_id          varchar(200) NOT NULL,
    entry_date         timestamp(6) NOT NULL,
    subject_class_name varchar(255) NOT NULL,
    subject_id         varchar(255) NOT NULL,
    header_text        varchar(255) NOT NULL,
    body_text          varchar(4000),
    id                 varchar(32) NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX misc_note_subject_index ON misc_note(subject_class_name, subject_id, header_text);
CREATE INDEX misc_note_subject_date_index ON misc_note(entry_date, subject_class_name, subject_id);
CREATE INDEX misc_note_editor_index ON misc_note(editor_id, entry_date);
CREATE INDEX misc_note_body_index ON misc_note(body_text);

CREATE TABLE subject (
    subject_id    varchar(32) NOT NULL,
    subclass_name varchar(255) NOT NULL,
    name          varchar(255),
    PRIMARY KEY (subject_id)
);
CREATE INDEX subject_name_index ON subject(name);

CREATE TABLE subject_attribute (
    subject_id      varchar(32) NOT NULL REFERENCES subject(subject_id),
    attribute_label varchar(64) NOT NULL,
    attribute_value varchar(512) NOT NULL,
    nomenclature    varchar(64) NOT NULL,
    PRIMARY KEY (subject_id, attribute_label, attribute_value, nomenclature)
);
CREATE INDEX subject_attribute_subject_id_index ON subject_attribute(subject_id);
CREATE INDEX subject_attribute_label_index ON subject_attribute(attribute_label);

CREATE TABLE genome_user (
    name  varchar(64),
    email varchar(255) NOT NULL,
    PRIMARY KEY (email)
);

CREATE TABLE project (
    id   varchar(64) NOT NULL,
    name varchar(200) NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX project_name_index ON project(name);

CREATE TABLE project_part (
    id              varchar(64) NOT NULL,
    project_id      varchar(64) NOT NULL REFERENCES project(id),
    part_class_name varchar(256) NOT NULL,
    part_id         varchar(64) NOT NULL,
    label           varchar(100),
    role            varchar(100),
    PRIMARY KEY (id),
    UNIQUE (project_id, part_class_name, part_id)
);
CREATE INDEX project_part_part_role_index ON project_part(part_class_name, part_id, role);
CREATE INDEX project_part_project_role_index ON project_part(project_id, role);
CREATE INDEX project_part_project_label_index ON project_part(project_id, label);

CREATE TABLE genome_task (
    id              varchar(255),
    command_class   varchar(255) NOT NULL,
    params          varchar(4096),
    stdout_pathname varchar(255),
    stderr_pathname varchar(255),
    status          varchar(50) NOT NULL,
    user_id         varchar(255) NOT NULL,
    submit_time     timestamp(6) DEFAULT current_timestamp NOT NULL,
    start_time      timestamp(6),
    end_time        timestamp(6),
    PRIMARY KEY (id)
);
