#!/gsc/bin/perl

use strict;
use warnings;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

use Test::More tests => 13;
use above "Genome";

BEGIN {
    use_ok('Genome::ProcessingProfile::Assembly');
}

my %params = (
              name => 'test',
              read_filter_name => 'seqclean',
              read_filter_params => 'test seqclean params',
              read_trimmer_name => 'sfffile',
              read_trimmer_params => 'test sfffile params',
              assembler_name => 'newbler',
              assembler_params => 'test newbler params',
              sequencing_platform => '454',
	      assembler_test => 1,
          );
my $assembly = Genome::ProcessingProfile::Assembly->create(%params);
isa_ok($assembly,'Genome::ProcessingProfile::Assembly');
for my $property_name (keys %params) {
    is($assembly->$property_name,$params{$property_name},$property_name .' accessor');
}
my $name = delete $params{name};
my @assembly_pps = Genome::ProcessingProfile::Assembly->get(%params);
is(scalar(@assembly_pps),1,"expected 1 assembly processing profile'");
is($assembly_pps[0]->name,$name,'found '. $name .' processing profile');
exit;
