#!/gsc/bin/perl

use strict;
use warnings;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

use Test::More tests => 5;
use above "Genome";

my $name = 'test';

my $read_filter = 'seq-clean';
my $read_trimmer = 'sff-file';
my $assembler = 'newbler';


my $assembly = Genome::ProcessingProfile::Assembly->create(
                                                           name => $name,
                                                           read_filter => $read_filter,
                                                           read_trimmer => $read_trimmer,
                                                           assembler => $assembler,
                                                       );
isa_ok($assembly,'Genome::ProcessingProfile::Assembly');
is($assembly->name,$name,'name accessor');
is($assembly->read_filter,$read_filter,'read_filter accessor');
is($assembly->read_trimmer,$read_trimmer,'read_trimmer accessor');
is($assembly->assembler,$assembler,'assembler accessor');

UR::Context->commit;

exit;
