#! /gsc/bin/perl

use strict;
use warnings;

use above 'Genome';

use Data::Dumper 'Dumper';
use Test::More;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

use_ok('Genome::Sample::Command::ImportDacc') or die;

UR::DataSource->next_dummy_autogenerated_id;
do {
    $UR::DataSource::last_dummy_autogenerated_id = int($UR::DataSource::last_dummy_autogenerated_id / 10);
} until length($UR::DataSource::last_dummy_autogenerated_id) < 9;
diag('Dummy ID: '.$UR::DataSource::last_dummy_autogenerated_id);
cmp_ok(length($UR::DataSource::last_dummy_autogenerated_id), '<',  9, 'dummy id is shorter than 9 chars');

# xml file import
my $dir = '/gsc/var/cache/testsuite/data/Genome-InstrumentData-Command-Dacc/SRS000000';
my @xml_files = glob($dir.'/*xml');
is(@xml_files, 2, 'Got 2 xml files');
note('xml file import');
my $import = Genome::Sample::Command::ImportDacc->create(
    sra_sample_id => 'SRS000000',
    xml_files => \@xml_files,
);
ok($import, 'create');
$import->dump_status_messages(1);
ok($import->execute, 'execute');

# basic import
note('basic import');
$import = Genome::Sample::Command::ImportDacc->create(
    sra_sample_id => 'SRS000000',
);
ok($import, 'create');
$import->dump_status_messages(1);
ok($import->execute, 'execute');

done_testing();
exit;

=pod

=head1 Tests

=head1 Disclaimer

 Copyright (C) 2010 Washington University Genome Sequencing Center

 This script is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY or the implied warranty of MERCHANTABILITY
 or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 License for more details.

=head1 Author(s)

 Eddie Belter <ebelter@watson.wustl.edu>

=cut

