#! /gsc/bin/perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
    $ENV{UR_COMMAND_DUMP_STATUS_MESSAGES} = 1;
};

use above 'Genome';

use Data::Dumper;
require File::Temp;
require File::Compare;
use Test::More;

use_ok('Genome::InstrumentData::Command::Microarray::Extract') or die;

my $testdir = '/gsc/var/cache/testsuite/data/Genome-InstrumentData-Command-Microarray';
my $testdir_version = $testdir.'/v2';
my $dbsnp_file = $testdir.'/dbsnp.132';
my $expected_output = $testdir_version.'/expected.output';
my $fl = Genome::Model::Tools::DetectVariants2::Result::Manual->__define__(
    description => '__TEST__DBSNP132__',
    username => 'apipe-tester',
    file_content_hash => 'c746fb7b7a88712d27cf71f8262dd6e8',
    output_dir => $testdir,
);
ok($fl, 'create dv2 result');
my $variation_list_build = Genome::Model::Build::ImportedVariationList->__define__(
    model => Genome::Model->get(2868377411),
    snv_result => $fl,
    version => 132,
);
ok($variation_list_build, 'create variation list build');

my $sample = Genome::Sample->__define__(
    name => '__TEST__SAMPLE__',
);
ok($sample, 'create sample');
my $library = Genome::Library->__define__(
    name => $sample->name.'-microarraylib',
    sample => $sample,
);
ok($library, 'create library');
my $instrument_data = Genome::InstrumentData::Imported->__define__(
    id => -7777,
    library => $library,
    import_format => 'genotype file',
    sequencing_platform => 'infinium',
);
ok(
    $instrument_data->add_attribute(attribute_label => 'genotype_file', attribute_value => $testdir_version.'/snpreport/-7777'),
    'add attr to inst data for genotype file',
);
ok($instrument_data, 'create instrument data');
$instrument_data->add_attribute(attribute_label => 'chip_name', attribute_value => 'test');
is($instrument_data->attributes(attribute_label => 'chip_name')->attribute_value, 'test', 'add attribute for chip name');
$instrument_data->add_attribute(attribute_label => 'version', attribute_value => '1');
is($instrument_data->attributes(attribute_label => 'version')->attribute_value, '1', 'add attribute for version');
$sample->default_genotype_data_id($instrument_data->id);

my $alloc_for_snpid_mapping = Genome::Disk::Allocation->__define__(
    disk_group_name => 'info_alignments',
    group_subdirectory => '',
    mount_path => $testdir_version,
    allocation_path => 'microarray_data/infinium-test-1',
);
ok($alloc_for_snpid_mapping, 'define snpid mapping allocation');

no warnings;
*Genome::FeatureList::file_path = sub{ return $dbsnp_file };
use warnings;

my $tmpdir = File::Temp::tempdir(CLEANUP => 1);
my $output = $tmpdir.'/genotypes.out';

my $cmd = Genome::InstrumentData::Command::Microarray::Extract->create(
    output => $output,
    sample => $sample,
    filters => [qw/ gc_score:min=0.7 /],
    fields => [qw/ chromosome position alleles id /],
    variation_list_build => $variation_list_build,
    use_default => 1,
);
ok($cmd, 'create');
ok($cmd->execute, 'execute');
is(File::Compare::compare($output, $expected_output), 0, 'output file matches');

#print "gvimdiff $output $expected_output\n"; <STDIN>;
done_testing();
exit;

