#!/gsc/bin/perl

use strict;
use warnings;

use above "Genome";
use Test::More;
use Data::Dumper;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

BEGIN {
    my $archos = `uname -a`;
    if ($archos !~ /64/) {
        plan skip_all => "Must run from 64-bit machine";
    } else {
        plan tests => 1;
    }
};

use_ok( 'Genome::Model::Tools::Somatic::SnpFilter');
