#!/gsc/bin/perl

use strict;
use warnings;

use above "Genome";
use Test::More tests => 2;
use Data::Dumper;
        
$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;


use_ok( 'Genome::Model::Tools::Somatic::Compare::CaptureBams');

my @workflow_errors = Genome::Model::Tools::Somatic::Compare::CaptureBams->_operation->validate;
is(scalar(@workflow_errors), 0, 'Workflow has no errors.');
