#!/usr/bin/env perl

use strict;
use warnings;

BEGIN {
    $ENV{UR_DBI_NO_COMMIT} = 1;
    $ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
}

use above 'Genome';
use Test::More;
use Carp::Always;
use Data::Dumper;

my $model_class = 'Genome::Model::Command::Define::ImportedAssembly';
my $model_name = "test-define-importedassembly-model-$$";
use_ok($model_class);

# set up required test data
my $data_dir = File::Temp::tempdir('DefineImportedAssemblyModelTest-XXXXX', DIR => '/gsc/var/cache/testsuite/running_testsuites', CLEANUP => 1);
my $individual = Genome::Individual->create(name => 'test-patient', common_name => 'testpatient');
my $sample = Genome::Sample->create(name => 'test-patient-sample', species_name => 'human', common_name => 'normal', source => $individual);

my $pp = Genome::ProcessingProfile::ImportedAssembly->create(
    name => 'test-imported-assembly-pp',
    assembler_name => 'something',
    );
ok($pp, 'created processing profile');

# begin testing
my $model = create_cmdline(
    "--processing-profile=" . $pp->id,
    "--subject-name=" . $sample->name,

);
ok($model, 'created model via command line with processing profile id');
is($model->name, $model_name, 'model name matches');
is($model->processing_profile->id, $pp->id, 'processing profile matches');
ok($model->delete, 'deleted model');

$model = create_cmdline(
    "--processing-profile-name=" . $pp->name,
    "--subject-name=" . $sample->name,

);
ok($model, 'created model via command line with processing profile name');
is($model->name, $model_name, 'model name matches');
is($model->processing_profile->id, $pp->id, 'processing profile matches');
ok($model->delete, 'deleted model');


$model = create_direct(
    processing_profile_id => $pp->id,
    subject_name => $sample->name,
);
ok($model, 'created model with processing profile id');
is($model->name, $model_name, 'model name matches');
is($model->processing_profile->id, $pp->id, 'processing profile matches');
ok($model->delete, 'deleted model');

$model = create_direct(
    processing_profile_name => $pp->name,
    subject_name => $sample->name,
);
ok($model, 'created model with processing profile name');
is($model->name, $model_name, 'model name matches');
is($model->processing_profile->id, $pp->id, 'processing profile matches');
ok($model->delete, 'deleted model');

done_testing();

sub create_cmdline {
    my @args = (@_, "--model-name=$model_name");
    my $rv = $model_class->_execute_with_shell_params_and_return_exit_code(@args);
    is($rv, 0, 'executed with command line args');
    return Genome::Model->get(name => $model_name);
}

sub create_direct {
    my @args = (@_, model_name => $model_name);
    my $cmd = $model_class->create(@args);
    ok($cmd && !$cmd->__errors__, 'created command without errors');
    ok($cmd->execute, 'executed on object directly');
    return Genome::Model->get($cmd->result_model_id);
}
