#!/usr/bin/env perl
use strict;
use warnings;

use above "Genome";
use Test::More;

$ENV{UR_DBI_NO_COMMIT} = 1;
$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;

UR::DataSource->next_dummy_autogenerated_id;
do {
    $UR::DataSource::last_dummy_autogenerated_id = int($UR::DataSource::last_dummy_autogenerated_id / 10);
} until length($UR::DataSource::last_dummy_autogenerated_id) < 9;
diag('Dummy ID: '.$UR::DataSource::last_dummy_autogenerated_id);
cmp_ok(length($UR::DataSource::last_dummy_autogenerated_id), '<',  9, 'dummy id is shorter than 9 chars');

use_ok('Genome::Site::WUGC::Taxon');

my $id = -54321;
my $taxon = Genome::Site::WUGC::Taxon->get($id);
ok(!$taxon, 'taxon does not exist');

$taxon = Genome::Site::WUGC::Taxon->create(
    #id => $id,
    name => 'Wookiee',
    domain => 'Unknown',
    strain_name => 'Short Hair',
    species_latin_name => 'Kashyyyk Wookiee',
    #ncbi_taxon_id => 
    #ncbi_taxon_species_name => 
    #locus_tag => 
    #gram_stain_category => 
    estimated_genome_size => 7000000000,
    #current_default_org_prefix => 
    #current_genome_refseq_id => 
    #model_member_id => 
    #_legacy_org_id => set in create
    #_next_amplicon_iteration => set in create
);
ok($taxon, "created a new genome taxon");
isa_ok($taxon, 'Genome::Site::WUGC::Taxon');
ok($taxon->id, "id is set");
is($taxon->subject_type, 'organism taxon', 'subject type is organism taxon');
print Data::Dumper::Dumper($taxon);

my $commit = eval{ UR::Context->commit; };
ok($commit, 'commit');

$taxon = Genome::Site::WUGC::Taxon->get(name => 'Wookiee');
ok($taxon, 'got new taxon');

done_testing();
exit();

