package GSCApp::Wikibot;

use warnings;
use strict;

use base 'GSCApp::MediaWiki';


sub new {

    my ($class) = @_;
    
    my $self = $class->SUPER::new(
        wiki_url            => 'https://gscweb/wiki',
        user_agent          => 'tester',
        ignore_user_cookies => 1,
    ) or die 'Could not create GSCApp::MediaWiki object for Wikibot';

    $self->login(
        user             => 'Wikibot',
        password         => 'w1k1_gsc_1',
        mediawiki_domain => 'local'
    ) or die 'Wikibot could not login';

    return $self;
}




1;



=pod

=head1 NAME

GSCApp::Wikibot

=head1 SYNOPSIS

use GSCApp::Wikibot;

my $wb = GSCApp::Wikibot->new();

my $src = $wb->get_page_source(page => 'User:Wikibot');

$src .= 'I like pie.';

$wb->post_page_to_wiki(page         => 'User:Wikibot',
                       page_text    => $src,
                       edit_summary => 'an edit about pie');

=head1 DESCRIPTION

Wikibot is used to update report/summary pages generated by cron-scheduled scripts.

see GSCApp::MediaWiki.

=cut

