use strict;
use warnings;

use Test::More;

$ENV{UR_USE_DUMMY_AUTOGENERATED_IDS} = 1;
$ENV{UR_DBI_NO_COMMIT} = 1;

use_ok('above', 'Genome');

my $user = Genome::Sys::User->create(
    email => 'leeroy@jenkins.org',
    name => 'Leeroy Jenkins',
    username => 'ljenkins',
);
isa_ok($user, 'Genome::Sys::User', '$user');

no warnings qw(redefine once);
local *Genome::Sys::username = sub { return $user->username };
use warnings qw(redefine once);
my $project = Genome::Project->create(name => 'Test Project (Project/View/Solr/Xml.t)');
isa_ok($project, 'Genome::Project', '$project');

my $project_view = Genome::Project::View::Solr::Xml->create(subject => $project);
isa_ok($project_view, 'UR::Object::View', '$project_view');
ok($project_view->content, 'generated content of project view');

done_testing();
